name 'poise-github'
maintainer 'Mathieu Sauve-Frankel'
maintainer_email 'msf@kisoku.net'
license 'apache2'
description 'manage github organizations with poise'
long_description 'manage github organizations with poise'
version '0.2.2'
issues_url 'https://github.com/kisoku/poise-github/issues'
source_url 'https://github.com/kisoku/poise-github'

depends 'poise'
